version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: todo_list
